// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingManager.API.Data;

#nullable disable

namespace ShoppingManager.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113042723_AddPurchaseUser")]
    partial class AddPurchaseUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingManager.API.Models.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("ShoppingManager.API.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("RefPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "LAPTOP001",
                            CreatedAt = new DateTime(2026, 1, 13, 4, 27, 23, 517, DateTimeKind.Utc).AddTicks(8069),
                            Description = "15.6-inch business laptop with Intel Core i7 processor",
                            Name = "Dell Latitude 5520 Laptop",
                            RefPrice = 1299.99m,
                            Unit = "PC"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "MOUSE001",
                            CreatedAt = new DateTime(2026, 1, 13, 4, 27, 23, 517, DateTimeKind.Utc).AddTicks(8074),
                            Description = "Advanced wireless mouse for productivity",
                            Name = "Logitech MX Master 3 Mouse",
                            RefPrice = 99.99m,
                            Unit = "PC"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "PAPER001",
                            CreatedAt = new DateTime(2026, 1, 13, 4, 27, 23, 517, DateTimeKind.Utc).AddTicks(8088),
                            Description = "500 sheets of white A4 copy paper",
                            Name = "A4 Copy Paper",
                            RefPrice = 4.99m,
                            Unit = "REAM"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "PEN001",
                            CreatedAt = new DateTime(2026, 1, 13, 4, 27, 23, 517, DateTimeKind.Utc).AddTicks(8092),
                            Description = "Set of 10 blue ballpoint pens",
                            Name = "Ballpoint Pen Set",
                            RefPrice = 12.50m,
                            Unit = "SET"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "MONITOR001",
                            CreatedAt = new DateTime(2026, 1, 13, 4, 27, 23, 517, DateTimeKind.Utc).AddTicks(8094),
                            Description = "Full HD 1920x1080 LED monitor",
                            Name = "Samsung 24-inch Monitor",
                            RefPrice = 249.99m,
                            Unit = "PC"
                        });
                });

            modelBuilder.Entity("ShoppingManager.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 4, 27, 23, 389, DateTimeKind.Utc).AddTicks(9388),
                            Email = "admin@shoppingmanager.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            PasswordHash = "$2a$11$BAwmy1TmtnSjhnP5JA5vru8pjSxinjOdUWcvdn2dH59uiY4sUA1AC",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 13, 4, 27, 23, 517, DateTimeKind.Utc).AddTicks(7380),
                            Email = "purchase@shoppingmanager.com",
                            FirstName = "Purchase",
                            IsActive = true,
                            LastName = "Manager",
                            PasswordHash = "$2a$11$A1aBucbOLFgh5MNsPhjnx.gPVNwhDLOhoLWv8blLqTQxVPVhKLtN2",
                            Role = 5
                        });
                });

            modelBuilder.Entity("ShoppingManager.API.Models.LoginHistory", b =>
                {
                    b.HasOne("ShoppingManager.API.Models.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoppingManager.API.Models.User", b =>
                {
                    b.Navigation("LoginHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
